<?php
declare(strict_types=1);

const DB_CONFIG_FILE = STORAGE_ROOT . '/database.php';

/** Return the saved MySQL settings, or fall back to complete APP_DB_* environment settings. */
function database_config(): ?array
{
    if (is_file(DB_CONFIG_FILE)) {
        try {
            $stored = require DB_CONFIG_FILE;
        } catch (Throwable $exception) {
            error_log('Could not read MySQL configuration: ' . $exception->getMessage());
            return null;
        }
        return is_array($stored) ? normalize_database_config($stored) : null;
    }

    $readEnvironment = static function (string $name, string $fallback = ''): string {
        $value = getenv($name);
        return $value === false ? $fallback : (string) $value;
    };
    $environment = [
        'host' => $readEnvironment('APP_DB_HOST'),
        'port' => $readEnvironment('APP_DB_PORT', '3306'),
        'database' => $readEnvironment('APP_DB_NAME'),
        'username' => $readEnvironment('APP_DB_USER'),
        'password' => $readEnvironment('APP_DB_PASSWORD'),
    ];
    if ($environment['host'] === '' || $environment['database'] === '' || $environment['username'] === '') {
        return null;
    }
    return normalize_database_config($environment);
}

function normalize_database_config(array $config): ?array
{
    $host = trim((string) ($config['host'] ?? ''));
    $database = trim((string) ($config['database'] ?? ''));
    $username = trim((string) ($config['username'] ?? ''));
    $password = (string) ($config['password'] ?? '');
    $port = filter_var($config['port'] ?? 3306, FILTER_VALIDATE_INT);

    if ($host === '' || strlen($host) > 255 || !preg_match('/^[A-Za-z0-9.\-:\[\]]+$/', $host)) {
        return null;
    }
    if ($database === '' || strlen($database) > 64 || !preg_match('/^[A-Za-z0-9_-]+$/', $database)) {
        return null;
    }
    if ($username === '' || strlen($username) > 128 || $port === false || $port < 1 || $port > 65535) {
        return null;
    }
    if (strlen($password) > 4096) {
        return null;
    }

    return [
        'host' => $host,
        'port' => (int) $port,
        'database' => $database,
        'username' => $username,
        'password' => $password,
        'charset' => 'utf8mb4',
    ];
}

function database_configured(): bool
{
    return database_config() !== null;
}

function connect_mysql(array $config): PDO
{
    $config = normalize_database_config($config);
    if ($config === null) {
        throw new InvalidArgumentException('Invalid MySQL connection settings.');
    }

    $dsn = 'mysql:host=' . $config['host']
        . ';port=' . $config['port']
        . ';dbname=' . $config['database']
        . ';charset=utf8mb4';

    $pdo = new PDO($dsn, $config['username'], $config['password'], [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
        PDO::ATTR_STRINGIFY_FETCHES => false,
        PDO::ATTR_TIMEOUT => 10,
    ]);
    $pdo->exec('SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci');
    return $pdo;
}

/** Store the connection secret outside the public web paths, under the protected storage/ folder. */
function save_database_config(array $config): void
{
    $config = normalize_database_config($config);
    if ($config === null) {
        throw new InvalidArgumentException('Invalid MySQL connection settings.');
    }
    if (!is_dir(STORAGE_ROOT) && !mkdir(STORAGE_ROOT, 0770, true) && !is_dir(STORAGE_ROOT)) {
        throw new RuntimeException('The storage directory could not be created.');
    }

    $path = DB_CONFIG_FILE;
    $temporaryPath = $path . '.' . bin2hex(random_bytes(8)) . '.tmp';
    $contents = "<?php\n// Generated by the one-time installer. Keep this file private.\nreturn " . var_export($config, true) . ";\n";
    if (file_put_contents($temporaryPath, $contents, LOCK_EX) !== strlen($contents)) {
        @unlink($temporaryPath);
        throw new RuntimeException('The MySQL configuration file could not be written.');
    }
    @chmod($temporaryPath, 0600);

    if (!@rename($temporaryPath, $path)) {
        // Windows may not replace an existing file with rename(); retain a backup while replacing it.
        $backupPath = $path . '.' . bin2hex(random_bytes(8)) . '.bak';
        $hasOldFile = is_file($path);
        if ($hasOldFile && !@rename($path, $backupPath)) {
            @unlink($temporaryPath);
            throw new RuntimeException('The existing MySQL configuration could not be replaced.');
        }
        if (!@rename($temporaryPath, $path)) {
            if ($hasOldFile) @rename($backupPath, $path);
            @unlink($temporaryPath);
            throw new RuntimeException('The MySQL configuration file could not be saved.');
        }
        if ($hasOldFile) @unlink($backupPath);
    }
    @chmod($path, 0600);
}

function db(): PDO
{
    static $pdo = null;
    if ($pdo instanceof PDO) {
        return $pdo;
    }

    $config = database_config();
    if ($config === null) {
        throw new RuntimeException('MySQL has not been configured.');
    }

    $pdo = connect_mysql($config);
    return $pdo;
}

function install_schema(PDO $pdo): void
{
    $tables = [
        <<<'SQL'
CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(300) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'employee',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    must_change_password TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    KEY idx_users_active_role (is_active, role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS site_settings (
    setting_key VARCHAR(191) NOT NULL,
    setting_value LONGTEXT NOT NULL,
    PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS content_items (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    type VARCHAR(32) NOT NULL,
    slug VARCHAR(191) NOT NULL DEFAULT '',
    title VARCHAR(300) NOT NULL,
    subtitle VARCHAR(600) NOT NULL DEFAULT '',
    excerpt MEDIUMTEXT NOT NULL,
    body MEDIUMTEXT NOT NULL,
    category VARCHAR(180) NOT NULL DEFAULT '',
    image_url VARCHAR(1000) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    is_published TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_content_type_published_order (type, is_published, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS contact_requests (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(300) NOT NULL,
    phone VARCHAR(60) NOT NULL,
    email VARCHAR(180) NOT NULL DEFAULT '',
    topic VARCHAR(200) NOT NULL DEFAULT '',
    message MEDIUMTEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'new',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_contact_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS attendance_challenges (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    token_hash CHAR(64) NOT NULL,
    created_by INT UNSIGNED NOT NULL,
    event_type VARCHAR(24) NOT NULL DEFAULT 'check_in',
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_attendance_challenge_token (token_hash),
    KEY idx_attendance_challenge_expiry (expires_at),
    CONSTRAINT fk_attendance_challenges_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS attendance_requests (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    method VARCHAR(24) NOT NULL,
    occurred_at DATETIME NOT NULL,
    latitude DOUBLE NULL,
    longitude DOUBLE NULL,
    accuracy DOUBLE NULL,
    challenge_id INT UNSIGNED NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    reviewed_by INT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    review_note VARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_attendance_user_time (user_id, occurred_at),
    KEY idx_attendance_status (status, occurred_at),
    CONSTRAINT fk_attendance_requests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_requests_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_attendance_requests_challenge FOREIGN KEY (challenge_id) REFERENCES attendance_challenges(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS attendance_qr_uses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    challenge_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    used_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_attendance_qr_use (challenge_id, user_id),
    KEY idx_attendance_qr_user (user_id),
    CONSTRAINT fk_attendance_qr_challenge FOREIGN KEY (challenge_id) REFERENCES attendance_challenges(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_qr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS workflow_items (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(300) NOT NULL,
    category VARCHAR(180) NOT NULL DEFAULT '',
    description MEDIUMTEXT NOT NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'normal',
    status VARCHAR(32) NOT NULL DEFAULT 'submitted',
    creator_id INT UNSIGNED NOT NULL,
    assignee_id INT UNSIGNED NULL,
    due_date DATE NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_workflow_creator (creator_id, id),
    KEY idx_workflow_assignee (assignee_id, status, id),
    CONSTRAINT fk_workflow_items_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_items_assignee FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS workflow_events (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    workflow_id INT UNSIGNED NOT NULL,
    actor_id INT UNSIGNED NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    from_status VARCHAR(32) NOT NULL DEFAULT '',
    to_status VARCHAR(32) NOT NULL DEFAULT '',
    note MEDIUMTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_workflow_events (workflow_id, id),
    CONSTRAINT fk_workflow_events_item FOREIGN KEY (workflow_id) REFERENCES workflow_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_events_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS chat_messages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sender_id INT UNSIGNED NOT NULL,
    recipient_id INT UNSIGNED NOT NULL,
    body MEDIUMTEXT NOT NULL,
    attachment_name VARCHAR(500) NOT NULL DEFAULT '',
    attachment_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attachment_type VARCHAR(150) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_chat_pair (sender_id, recipient_id, id),
    KEY idx_chat_recipient (recipient_id, sender_id, id),
    CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_messages_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
        <<<'SQL'
CREATE TABLE IF NOT EXISTS chat_signals (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sender_id INT UNSIGNED NOT NULL,
    recipient_id INT UNSIGNED NOT NULL,
    message_id INT UNSIGNED NOT NULL,
    signal_type VARCHAR(32) NOT NULL,
    payload MEDIUMTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_chat_signals_receiver (recipient_id, id),
    KEY idx_chat_signals_message (message_id),
    CONSTRAINT fk_chat_signals_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_signals_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_signals_message FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL,
    ];

    foreach ($tables as $statement) {
        $pdo->exec($statement);
    }

    // Additive migrations for databases created by earlier MySQL builds.
    $migrations = [
        'users' => ['must_change_password' => 'TINYINT(1) NOT NULL DEFAULT 0'],
        'attendance_challenges' => ['event_type' => "VARCHAR(24) NOT NULL DEFAULT 'check_in'"],
    ];
    $columnLookup = $pdo->prepare('SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :table');
    foreach ($migrations as $table => $columns) {
        $columnLookup->execute([':table' => $table]);
        $existingColumns = $columnLookup->fetchAll(PDO::FETCH_COLUMN);
        foreach ($columns as $column => $definition) {
            if (!in_array($column, $existingColumns, true)) {
                $pdo->exec('ALTER TABLE `' . $table . '` ADD COLUMN `' . $column . '` ' . $definition);
            }
        }
    }

    $defaults = [
        'site_name' => 'شرکت مشاوران افق دانش ثریا',
        'hero_label' => 'مشاوران مهندسی؛ همراه توسعه‌ای پایدار',
        'hero_title' => "مهندسیِ دقیق،\nبرای افق‌های روشن.",
        'hero_subtitle' => 'از نخستین ایده تا تصمیم‌های اجرایی، در کنار شما هستیم تا مسیر پروژه‌ها روشن‌تر، سنجیده‌تر و اثربخش‌تر باشد.',
        'hero_button' => 'گفت‌وگو با کارشناسان',
        'home_story' => 'در افق دانش ثریا، هر پروژه با شنیدن دقیق نیاز کارفرما آغاز می‌شود. ما دانش مهندسی را با نگاهی یکپارچه و مسئولانه همراه می‌کنیم تا تصمیم‌های امروز، پایه‌ای مطمئن برای فردا باشند.',
        'about_story' => 'افق دانش ثریا با این باور شکل گرفت که راه‌حل مهندسی زمانی ارزشمند است که در کنار دقت فنی، به نیاز واقعی انسان‌ها و آینده پروژه نیز پاسخ دهد. این نگاه، پایه همکاری ما با کارفرمایان و هم‌تیمی‌های تخصصی است.',
        'services_intro' => 'از شناخت مسئله و مطالعات اولیه تا طراحی، مدیریت و نظارت؛ خدمات ما متناسب با نیاز هر پروژه و در تعامل نزدیک با کارفرما تعریف می‌شود.',
        'value_1_title' => 'دقت و کیفیت',
        'value_1_text' => 'پایبندی به جزئیات، استانداردهای حرفه‌ای و تصمیم‌گیری مبتنی بر دانش.',
        'value_2_title' => 'مسئولیت‌پذیری',
        'value_2_text' => 'پاسخ‌گویی شفاف و توجه به اثر هر تصمیم در تمام چرخه پروژه.',
        'value_3_title' => 'همکاری',
        'value_3_text' => 'هم‌فکری با کارفرما و متخصصان برای رسیدن به راه‌حل‌های عملی.',
        'value_4_title' => 'نگاه آینده‌نگر',
        'value_4_text' => 'توجه به پایداری، تاب‌آوری و ارزش بلندمدت در انتخاب راهکارها.',
        'office_hours' => 'ساعات اداری شرکت را وارد کنید',
        'contact_phone_display' => 'شماره تماس شرکت (برای تکمیل)',
        'contact_phone_href' => '',
        'contact_email_display' => 'ایمیل شرکت (برای تکمیل)',
        'contact_email' => '',
        'contact_address' => 'نشانی دفتر شرکت را وارد کنید',
        'bale_display' => 'شناسه بله (برای تکمیل)',
        'bale_url' => '',
        'telegram_display' => 'شناسه تلگرام (برای تکمیل)',
        'telegram_url' => '',
    ];
    $insertSetting = $pdo->prepare('INSERT IGNORE INTO site_settings(setting_key, setting_value) VALUES(:key, :value)');
    foreach ($defaults as $key => $value) {
        $insertSetting->execute([':key' => $key, ':value' => $value]);
    }

    $seedMarker = $pdo->query("SELECT setting_value FROM site_settings WHERE setting_key = '_default_services_seeded'")->fetchColumn();
    if ($seedMarker !== '1') {
        $now = date('Y-m-d H:i:s');
        $services = [
            ['مطالعات و مشاوره مهندسی', 'شناخت دقیق نیازها و ارزیابی گزینه‌ها', 'تهیه مطالعات اولیه، امکان‌سنجی و ارائه مسیرهای اجرایی متناسب با اهداف پروژه.', 'مطالعات'],
            ['طراحی و اسناد فنی', 'از ایده تا نقشه‌های قابل اجرا', 'تدوین راهکارهای طراحی و اسناد فنی با توجه به الزامات پروژه و هماهنگی رشته‌های تخصصی.', 'طراحی'],
            ['مدیریت و کنترل پروژه', 'برنامه‌ریزی، هماهنگی و پایش', 'پشتیبانی از مدیریت زمان، هزینه، ریسک و هماهنگی ذی‌نفعان در مسیر اجرای پروژه.', 'مدیریت'],
            ['نظارت و ارزیابی فنی', 'کیفیت، ایمنی و انطباق', 'ارزیابی روند اجرا و ارائه گزارش‌های فنی برای کمک به تحقق اهداف و الزامات قرارداد.', 'نظارت'],
        ];
        $insertService = $pdo->prepare('INSERT INTO content_items(type, slug, title, subtitle, excerpt, body, category, sort_order, is_published, created_at, updated_at) VALUES(:type, :slug, :title, :subtitle, :excerpt, :body, :category, :sort, 1, :created, :updated)');
        foreach ($services as $index => $service) {
            $insertService->execute([
                ':type' => 'services',
                ':slug' => 'service-' . ($index + 1),
                ':title' => $service[0],
                ':subtitle' => $service[1],
                ':excerpt' => $service[2],
                ':body' => $service[2],
                ':category' => $service[3],
                ':sort' => $index + 1,
                ':created' => $now,
                ':updated' => $now,
            ]);
        }
        $markSeeded = $pdo->prepare('INSERT INTO site_settings(setting_key, setting_value) VALUES(:key, :value) ON DUPLICATE KEY UPDATE setting_value = :updated_value');
        $markSeeded->execute([':key' => '_default_services_seeded', ':value' => '1', ':updated_value' => '1']);
    }
}
